# Generated by Django 5.0.6 on 2025-03-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_todoitem_user_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
